import {
  ArrowLeft,
  Blocks,
  Check,
  ChevronRight,
  CircleAlert,
  Clock3,
  Code2,
  Copy,
  Ellipsis,
  ExternalLink,
  FileSignature,
  Globe2,
  Info,
  Link2,
  LoaderCircle,
  LockKeyhole,
  MessageSquareText,
  Moon,
  Network,
  Palette,
  Plus,
  QrCode,
  Radio,
  RefreshCw,
  Repeat2,
  ScanLine,
  Settings,
  Shield,
  ShieldCheck,
  Smartphone,
  Sun,
  Trash2,
  TriangleAlert,
  WifiOff,
  X,
  createElement,
  type IconNode
} from 'lucide';

const iconNodes = {
  'arrow-left': ArrowLeft,
  blocks: Blocks,
  check: Check,
  'chevron-right': ChevronRight,
  'circle-alert': CircleAlert,
  clock: Clock3,
  code: Code2,
  copy: Copy,
  ellipsis: Ellipsis,
  external: ExternalLink,
  signature: FileSignature,
  globe: Globe2,
  info: Info,
  link: Link2,
  loader: LoaderCircle,
  lock: LockKeyhole,
  message: MessageSquareText,
  moon: Moon,
  network: Network,
  palette: Palette,
  plus: Plus,
  qr: QrCode,
  radio: Radio,
  refresh: RefreshCw,
  switch: Repeat2,
  scan: ScanLine,
  settings: Settings,
  shield: Shield,
  'shield-check': ShieldCheck,
  phone: Smartphone,
  sun: Sun,
  trash: Trash2,
  warning: TriangleAlert,
  offline: WifiOff,
  x: X
} satisfies Record<string, IconNode>;

export type IconName = keyof typeof iconNodes;

export function icon(name: IconName, size = 18, className = '') {
  const node = createElement(iconNodes[name], {
    width: size,
    height: size,
    class: `lucide-icon${className ? ` ${className}` : ''}`,
    'aria-hidden': 'true',
    'stroke-width': '1.8'
  });
  return node as SVGElement;
}
